### ISSUE TITLE
Make the dashboard app responsive

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#551]
## Description

Right now, there are some components in the dashboard that are not responsive yet. It would be nice to make them responsive so that people can use it on their phones, tablets, etc. 

## Tasks

These are the issues related to making the dashboard app responsive. Feel free to create new issues if you find other components or pages that are not responsive yet.

- [x] https://github.com/bandada-infra/bandada/issues/553
- [x] https://github.com/bandada-infra/bandada/issues/557
- [x] https://github.com/bandada-infra/bandada/issues/558
- [x] https://github.com/bandada-infra/bandada/issues/559
- [x] https://github.com/bandada-infra/bandada/issues/641

**Comment by Benjtalkshow** [comment]
Hello @vplasencia ,
I can easily fix this issue if it is assigned to me. Can this issue be assigned to me? thanks.

**Comment by vplasencia** [comment]
Hey @Benjtalkshow I just assigned this issue to you.

**Comment by vplasencia** [comment]
Feel free to ask any questions.

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow I just assigned this issue to you.

Thanks

**Comment by vplasencia** [comment]
Hey @Benjtalkshow 

Can you add a comment in the issue I haven't assigned to you yet so that I can assign it?

**Comment by Benjtalkshow** [comment]
> Hey @Benjtalkshow
> 
> Can you add a comment in the issue I haven't assigned to you yet so that I can assign it?

Ok

**Comment by vplasencia** [comment]
Hey @Benjtalkshow!

Since there hasn’t been much activity on these issues recently, I’ll unassign them so others can work on them. If you’d still like to work on any of the issues, please let us know.

Thank you for your understanding and interest!

**Comment by yagopajarino** [comment]
Created #641 related to this

**Comment by vplasencia** [comment]
Thank you very much @yagopajarino! I just updated the description of this issue.
