### ISSUE TITLE
Improve client app

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#612]
## Description

It would be nice to improve the client app so that it is easier for people to use it and also check it to build their own.

## Tasks

- [x] Use API SDK for the credential groups.
- [x] Support multiple credential groups.
- [x] Use the latest Semaphore version for the identity package.
